In [3]:
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
hetero_list =  [ 1,2,3.0, 'text', True, 3+2j ]


In [4]:
student_marks = [78, 47, 96, 55, 34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)


[83, 52, 101, 60, 39]


In [5]:
%%time
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
    


CPU times: total: 62.5 ms
Wall time: 111 ms


In [1]:
%%time
import numpy as np
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b


CPU times: total: 0 ns
Wall time: 66.4 ms


In [2]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr


array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [5]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.shape


(3, 5)

In [6]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype


dtype('int32')

In [7]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)


[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [8]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1]


'buick skylark 320'

In [9]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [10]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0]


array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino'], dtype='<U25')

In [11]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,1]


'buick skylark 320'

In [15]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[1]


array(['130', '165', '150', '150', '140'], dtype='<U25')

In [12]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,1]


'buick skylark 320'

In [4]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,-1]


'ford torino'

In [3]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1:4]


array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [19]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U25')

In [33]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:2]


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [32]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:2, 3:5]


array([['amc rebel sst', 'ford torino'],
       ['150', '140']], dtype='<U25')

In [31]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:3, 0:3]


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U25')

In [30]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower = ",np.mean(horsepower_arr))


Mean horsepower =  147.0


In [29]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Median horsepower = ",np.median(horsepower_arr))


Median horsepower =  150.0


In [28]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))


Minimum horsepower:  130
Maximum horsepower:  165


In [1]:
import numpy as np
hr=np.array([130,165,150,150,140])
x=np.where(hr>=150)
print(x)
print(hr[x])

(array([1, 2, 3], dtype=int64),)
[165 150 150]


In [4]:
array11= np.array ([[67,45],[90,92],[66,72],[32,40]])
array11

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [5]:
array11= np.array ([[67,45],[90,92],[66,72],[32,40]])
add_marks=([5,10])
x=np.add(array11,add_marks)
x


array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

In [9]:
steps = np.array([[1,6012],[2,7879],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
print(steps)
steps_walked = np.array([6012,7879,6886,7230,4598,5564,6971,7763,8032,9569])

add_step = np.array([0,2000])
steps2 = np.add(steps,add_step)
print('steps after 7pm =',steps2)

x = np.where(steps_walked>9000)
print(steps_walked[x])

sorted_steps = np.sort(steps_walked)
print(sorted_steps)

[[   1 6012]
 [   2 7879]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
steps after 7pm = [[    1  8012]
 [    2  9879]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[9569]
[4598 5564 6012 6886 6971 7230 7763 7879 8032 9569]


In [7]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr))
print(np.sum(arr, axis=0)) 
print(np.sum(arr, axis=1))


10
[4 6]
[3 7]


In [8]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.mean(arr))
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1)) 

2.5
[2. 3.]
[1.5 3.5]


In [12]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.max(arr)) 
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))
print(np.min(arr)) 
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))

4
[3 4]
[2 4]
1
[1 2]
[1 3]


In [10]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.median(arr))
print(np.median(arr, axis=0)) 
print(np.median(arr, axis=1))


2.5
[2. 3.]
[1.5 3.5]


In [11]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.prod(arr))
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))


24
[3 8]
[ 2 12]


In [13]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr)) 
print(np.std(arr, axis=0)) 
print(np.std(arr, axis=1)) 

1.118033988749895
[1. 1.]
[0.5 0.5]


In [14]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.var(arr))
print(np.var(arr, axis=0)) 
print(np.var(arr, axis=1)) 

1.25
[1. 1.]
[0.25 0.25]


In [15]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [16]:
import numpy as np
arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(result) 


[3 3 3]


In [17]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result)

[ 4 10 18]


In [18]:
import numpy as np
arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 3, 4])
result = arr1 / arr2
print(result)

[2. 2. 2.]


In [19]:
import numpy as np
arr = np.array([2, 3, 4])
result = arr ** 2
print(result)

[ 4  9 16]


In [20]:
import numpy as np
arr = np.array([4, 9, 16])
result = np.sqrt(arr)
print(result)

[2. 3. 4.]


In [21]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 3])
result = arr1 == arr2
print(result) 

[False  True  True]


In [22]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_mean = np.mean(arr)
result_std = np.std(arr, axis=1)
result_sum = np.sum(arr, axis=0)
print(result_mean) 
print(result_std) 
print(result_sum)

3.5
[0.81649658 0.81649658]
[5 7 9]


In [23]:
import numpy as np
arr = np.array([2.3, 4.7, 6.1])
result = np.round(arr)
print(result)

[2. 5. 6.]


In [24]:
import numpy as np
arr = np.array([2, 3, 4])
result = np.power(arr, 2)
print(result) 

[ 4  9 16]


In [25]:
import numpy as np
arr = np.array([1, 5, 10])
result = np.where(arr < 5, arr, 0)
print(result) 

[1 0 0]


In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.cumsum(arr)
print(result) 

[ 1  3  6 10 15]


In [27]:
import numpy as np
arr = np.array([3, 1, 4, 2, 5])
result = np.sort(arr)
print(result) 

[1 2 3 4 5]


In [30]:
quarterly_difference = S_Y - S_X
print(quarterly_difference)


[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [31]:
less_than_2 = S_X < 2
print(less_than_2)


[[False False False False]
 [False False False False]]


In [32]:
X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)
# [[ 2 7 13 18]
# [ 4 12 18 23]]
print( X_cumsum >= 8)


[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]


In [33]:
yearly_mean_X = np.mean(S_X, axis=1)
print(yearly_mean_X)

[4.5  5.75]


In [34]:
quarterly_mean_Y = np.mean(S_Y, axis=0)
print(quarterly_mean_Y)


[6.5 6.  5.5 6.5]


In [35]:
numbers = [1, 2, 3, 4, 5]
squared_numbers = map(lambda x: x ** 2, numbers)
print(list(squared_numbers)) 

[1, 4, 9, 16, 25]


In [36]:
numbers = [1, 2, 3, 4, 5]
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers)) 

[2, 4]


In [37]:
from functools import reduce
numbers = [1, 2, 3, 4, 5]
sum_of_numbers = reduce(lambda x, y: x + y, numbers)
print(sum_of_numbers) 

15


In [2]:
square = lambda x: x ** 2
print(square(9))

81
